// assets/data/sounds.ts
export const SliderData = [
  {
    id: 'bell',
    label: 'Bell',
    png: require('../assets/images/bell.png'),
    gif: require('../assets/images/bell_anim.gif'),
    sound: require('../assets/sounds/bell.mp3'),
  },
  {
    id: 'bird',
    label: 'Bird',
    png: require('../assets/images/bird.png'),
    gif: require('../assets/images/bird_anim.gif'),
    sound: require('../assets/sounds/bird.mp3'),
  },
  {
    id: 'fire',
    label: 'Fire',
    png: require('../assets/images/fire.png'),
    gif: require('../assets/images/fire_anim.gif'),
    sound: require('../assets/sounds/fire.mp3'),
  },
  {
    id: 'flute',
    label: 'Flute',
    png: require('../assets/images/flute.png'),
    gif: require('../assets/images/flute_anim.gif'),
    sound: require('../assets/sounds/flute.mp3'),
  },
  {
    id: 'frog',
    label: 'Frog',
    png: require('../assets/images/frog.png'),
    gif: require('../assets/images/frog_anim.gif'),
    sound: require('../assets/sounds/frog.mp3'),
  },
  {
    id: 'ice_cracking',
    label: 'Ice Cracking',
    png: require('../assets/images/ice_cracking.png'),
    gif: require('../assets/images/ice_cracking_anim.gif'),
    sound: require('../assets/sounds/ice_cracking.mp3'),
  },
  {
    id: 'ocean',
    label: 'Ocean',
    png: require('../assets/images/ocean.png'),
    gif: require('../assets/images/ocean_anim.gif'),
    sound: require('../assets/sounds/ocean.mp3'),
  },
  {
    id: 'om',
    label: 'Om',
    png: require('../assets/images/om.png'),
    gif: require('../assets/images/om_anim.gif'),
    sound: require('../assets/sounds/om.mp3'),
  },
  {
    id: 'owl',
    label: 'Owl',
    png: require('../assets/images/owl.png'),
    gif: require('../assets/images/owl_anim.gif'),
    sound: require('../assets/sounds/owl.mp3'),
  },
  {
    id: 'rain',
    label: 'Rain',
    png: require('../assets/images/rain.png'),
    gif: require('../assets/images/rain_anim.gif'),
    sound: require('../assets/sounds/rain.mp3'),
  },
  {
    id: 'thunder',
    label: 'Thunder',
    png: require('../assets/images/thunder.png'),
    gif: require('../assets/images/thunder_anim.gif'),
    sound: require('../assets/sounds/thunder.mp3'),
  },
  {
    id: 'tibetan_bowls',
    label: 'Tibetan Bowls',
    png: require('../assets/images/tibetan_bowl.png'),
    gif: require('../assets/images/tibetan_bowl_anim.gif'),
    sound: require('../assets/sounds/tibetan_bowls.mp3'),
  },
  {
    id: 'train',
    label: 'Train',
    png: require('../assets/images/train.png'),
    gif: require('../assets/images/train_anim.gif'),
    sound: require('../assets/sounds/train.mp3'),
  },
  {
    id: 'wind_chimes',
    label: 'Wind Chimes',
    png: require('../assets/images/wind_chimes.png'),
    gif: require('../assets/images/wind_chimes_anim.gif'),
    sound: require('../assets/sounds/wind_chimes.mp3'),
  },

  {
    id: 'wind',
    label: 'Wind',
    png: require('../assets/images/wind.png'),
    gif: require('../assets/images/wind_anim.gif'),
    sound: require('../assets/sounds/wind.mp3'),
  },
];
